name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dos:
    runs-on: windows-latest
  
  mac:
    runs-on: macos-latest
    
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: make setup
    - name: compile
      run: make compile
